package com.smetrix.app.utils.quantity;

public enum QuantityCalculationMethod {
    MANUAL_QUANTITY,

    AREA_FLOOR,
    AREA_WALLS,
    AREA_CEILING,
    AREA_ALL_SURFACES,
    AREA_MANUAL,

    VOLUME_ROOM,
    VOLUME_AREA_THICKNESS,
    VOLUME_MANUAL,

    LENGTH_PERIMETER,
    LENGTH_PERIMETER_MINUS_OPENINGS,
    LENGTH_MANUAL,

    CONSUMPTION_PER_M2,
    CONSUMPTION_PER_M3,
    CONSUMPTION_PER_METER,
    CONSUMPTION_PER_PIECE,

    PIECES_MANUAL,
    PIECES_BY_DOORS,
    PIECES_BY_WINDOWS,
    PIECES_BY_AREA_COVERAGE,

    PACKAGES_MANUAL,
    PACKAGES_BY_COVERAGE,
    PACKAGES_BY_WEIGHT,
    PACKAGES_BY_VOLUME,

    UNKNOWN_MANUAL
}
